import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowRight, CheckCircle2, Download, FileText, Fingerprint, ShieldCheck, Sparkles, UserCheck } from 'lucide-react';
import type { DocumentRecord, Review, Signal, User } from '../types';
import { download, fileBlob, post } from '../services/api';
import { Badge, Empty, ErrorBox, Modal, MockLabel, Panel, dateTime, percent, pretty } from './ui';

export function ScoreCards({ review }: {review: Review}) {
  const verified = review.verifications.filter(v=>v.status==='VERIFIED').length;
  return <div className="review-score-grid"><div className="review-score-card"><span className="score-card-label">Compliance score <ShieldCheck size={17}/></span><div><strong>{review.compliance_score ?? '—'}</strong><span>/ 100</span></div><div className="wide-track"><span style={{width:`${review.compliance_score || 0}%`}}/></div><p>Weighted, evidence-backed assessment</p></div><div className="review-score-card risk-score"><span className="score-card-label">Risk assessment <AlertTriangle size={17}/></span><div><strong>{review.risk_score ?? '—'}</strong><span>/ 100</span><Badge value={review.risk_level}/></div><p>{review.risk?.contributing_factors.length || 0} contributing risk signals</p></div><div className="review-score-card"><span className="score-card-label">Source verification <Fingerprint size={17}/></span><div><strong>{verified}</strong><span>/ {review.verifications.length || 11}</span></div><p>{review.verifications.length-verified} checks need officer attention</p><MockLabel/></div></div>;
}

export function SourceVerificationTable({ review, onDocument }: {review: Review; onDocument: (doc: DocumentRecord)=>void}) {
  const [source, setSource] = useState('ALL');
  return <Panel title="Authorised-source verification" subtitle="Submitted identifiers compared with fictional source records" action={<MockLabel/>}><div className="toolbar"><select aria-label="Filter source checks" value={source} onChange={e=>setSource(e.target.value)}><option value="ALL">All source checks</option><option value="ATTENTION">Needs attention</option><option value="VERIFIED">Demo verified</option></select><span className="toolbar-count">{review.verifications.length} source records</span></div>{!review.verifications.length ? <Empty title="Source checks have not run">Start an AI compliance review to verify extracted identifiers.</Empty> : <div className="table-scroll"><table className="verification-table"><thead><tr><th>Source</th><th>Extracted value</th><th>Source record</th><th>Status</th><th>Confidence</th><th>Evidence</th></tr></thead><tbody>{review.verifications.filter(v=>source==='ALL'||(source==='VERIFIED'?v.status==='VERIFIED':v.status!=='VERIFIED')).map(v=>{const doc=review.documents.find(d=>d.id===v.evidence.document_id);return <tr key={v.id} className={v.status==='MISMATCH'?'flagged-row':''}><td><strong>{pretty(v.source)}</strong><small className="block-small">{dateTime(v.checked_at)}</small></td><td><code className={v.status==='MISMATCH'?'field-mismatch':''}>{v.identifier || 'Not extracted'}</code></td><td><code>{v.evidence.source_value || 'Not available'}</code><small className="block-small">{String(v.record.status || 'No source record')}</small></td><td><Badge value={v.status}/></td><td>{percent(v.confidence)}</td><td><details className="evidence-details"><summary>Inspect</summary><p>{v.evidence.reason}</p><code>{v.id}</code>{doc && <button className="text-button" onClick={()=>onDocument(doc)}><FileText size={14}/> Open page {v.evidence.source_page || 1}</button>}</details></td></tr>;})}</tbody></table></div>}</Panel>;
}

export function ComplianceMatrix({ review, onDocument }: {review: Review; onDocument: (doc: DocumentRecord)=>void}) {
  return <div className="stack"><Panel title="Tender compliance matrix" subtitle={`${review.compliance.filter(r=>r.status==='PASS').length} of ${review.compliance.length} enabled rules passed`}><div className="rule-list">{review.compliance.map(r=><details className="rule-result" key={r.result_id}><summary><span className={`rule-icon ${r.status==='PASS'?'pass':'fail'}`}>{r.status==='PASS'?<CheckCircle2 size={18}/>:<AlertTriangle size={18}/>}</span><span><small>{r.rule_code} · {pretty(r.category)}</small><strong>{r.name}</strong></span><Badge value={r.status}/></summary><div className="rule-evidence"><p>{r.explanation}</p><div className="evidence-tag">{r.required?'Mandatory':'Advisory'} · {pretty(r.severity)} severity</div>{r.evidence.map((e,i)=>{const doc=review.documents.find(d=>d.id===e.document_id)||review.documents.find(d=>d.id===review.entities.find(x=>x.id===e.entity_id)?.document_id); return <div key={i} className="rule-evidence-item"><code>{e.extracted || e.filename || e.status || e.source || 'Evidence record'}</code>{e.source_value && <span>Source: <code>{e.source_value}</code></span>}{doc && <button className="text-button" onClick={()=>onDocument(doc)}>Open {doc.filename} <ArrowRight size={13}/></button>}</div>;})}<small className="subtle">Rule result: {r.result_id}</small></div></details>)}</div></Panel>{review.risk && <Panel title="How the compliance score is calculated" subtitle={review.risk.compliance.method}><div className="score-breakdown">{review.risk.compliance.breakdown.map(part=><details key={part.component}><summary><span>{part.component}<small>{part.passed} / {part.total} checks</small></span><div className="breakdown-track"><i style={{width:`${part.weight ? part.earned/part.weight*100 : 0}%`}}/></div><strong>{part.earned}<small> / {part.weight}</small></strong></summary><ul>{part.evidence.map((text,i)=><li key={i}>{text}</li>)}</ul></details>)}</div></Panel>}</div>;
}

export function RiskAnalysis({review}: {review: Review}) {
  if(!review.risk) return <Empty title="Risk assessment pending">Start a verification run to calculate risk from evidence.</Empty>;
  return <div className="stack"><Panel title="Contributing risk signals" subtitle={review.risk.method}><div className="risk-signals">{review.risk.contributing_factors.length ? review.risk.contributing_factors.map(s=><div className="risk-signal" key={s.id}><AlertTriangle size={20}/><div><strong>{pretty(s.type)}</strong><p>{s.description}</p><small>{s.rule_result_ids.length} linked tender rule result(s)</small></div><b>+{s.points}<small>risk points</small></b></div>):<Empty title="No rule-based risk signals">All configured checks passed for this run.</Empty>}</div></Panel><div className="two-col"><Panel title="Identity consistency" subtitle="Name and identifier matching with explicit thresholds"><div className="content-pad">{review.risk.identity_checks.map(c=><div className="identity-check" key={c.label}><div><strong>{c.label}</strong><Badge value={c.status}/></div>{c.left && <p>{c.left}<br/><span>Source: {c.right}</span></p>}{c.similarity!==undefined && <small>{percent(c.similarity)} similarity · {c.provider}</small>}</div>)}<p className="subtle">Default thresholds: match ≥95%; review 80–95%; mismatch &lt;80%.</p></div></Panel><Panel title="Anomaly analysis" subtitle={review.risk.anomaly.detector}><div className="content-pad"><div className="anomaly-number">{review.risk.anomaly.anomaly_score ?? '—'}<span>model anomaly score</span></div><p className="subtle">{review.risk.anomaly.explanation}</p><details className="feature-details"><summary>Inspect detector features</summary>{Object.entries(review.risk.anomaly.features).map(([k,v])=><div className="label-value" key={k}><span>{pretty(k)}</span><strong>{typeof v==='number'?Math.round(v*100)/100:v}</strong></div>)}</details></div></Panel></div></div>;
}

export function RecommendationPanel({review, onDecide, canDecide}: {review: Review; onDecide:()=>void; canDecide:boolean}) {
  if(!review.ai) return <Empty title="AI explanation pending">The explanation is generated after source, rule, and risk checks finish.</Empty>;
  return <div className="stack"><Panel className="ai-panel"><div className="ai-header"><span className="ai-mark"><Sparkles size={23}/></span><div><div className="eyebrow">EVIDENCE-GROUNDED DECISION SUPPORT</div><h2>AI Verification Summary</h2></div><span className="advisory-chip">ADVISORY ONLY</span></div><div className="ai-body"><p>{review.ai.summary}</p><div className="ai-action"><div><small>RECOMMENDED OFFICER ACTION</small><h3>{review.ai.recommended_action}</h3></div><UserCheck size={27}/></div><h3>Why this recommendation?</h3><ul>{review.ai.why.map((reason,i)=><li key={i}>{reason}</li>)}</ul><div className="ai-confidence"><ShieldCheck size={18}/><div><strong>Evidence confidence: {percent(review.ai.confidence)}</strong><p>{review.ai.confidence_explanation}</p></div></div><p className="subtle">{review.ai.officer_action}</p>{canDecide && <button className="button primary section-gap" onClick={onDecide}><UserCheck size={17}/> Record officer decision <ArrowRight size={16}/></button>}</div><div className="ai-provider">{review.ai.provider} <MockLabel/></div></Panel><Panel title="AI reasoning sources" subtitle="Retrieved tender rules and internal demo guidance"><div className="reasoning-sources">{review.ai.reasoning_sources.sources.map(s=><details key={s.id}><summary><FileText size={17}/><span><strong>{s.title}</strong><small>{s.kind} · Retrieval relevance {s.relevance}</small></span></summary><p>{s.text}</p></details>)}<div className="retrieval-meta">{review.ai.reasoning_sources.vector_provider}<br/>{review.ai.reasoning_sources.embedding_provider}<p>{review.ai.reasoning_sources.scope}</p></div></div></Panel></div>;
}

export function OfficerDecisionModal({review,onClose,onSaved}: {review:Review;onClose:()=>void;onSaved:()=>void}) {
  const [decision,setDecision]=useState('NEEDS CLARIFICATION'),[reason,setReason]=useState(''),[comments,setComments]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function save(){setBusy(true);try{await post(`/bids/${review.id}/decision`,{run_id:review.run?.id,decision,reason,comments});onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal title="Record officer decision" onClose={onClose}><form onSubmit={e=>{e.preventDefault();void save();}}><div className="modal-body"><ErrorBox message={error}/><div className="inline-notice">AI recommendation: <strong>{review.ai?.recommended_action}</strong><br/>Your decision is recorded separately. You retain final authority.</div><label className="section-gap">Final decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option>NEEDS CLARIFICATION</option><option>QUALIFIED</option><option>DISQUALIFIED</option></select></label><label>Decision or override reason <span className="required">*</span><textarea value={reason} onChange={e=>setReason(e.target.value)} required minLength={5} maxLength={4000} placeholder="Explain the evidence supporting your decision…"/></label><label>Additional comments (optional)<textarea value={comments} onChange={e=>setComments(e.target.value)} maxLength={4000}/></label><p className="subtle section-gap">Reviewer, timestamp, evidence references, and your reason will be appended to the audit chain.</p></div><div className="modal-actions"><button type="button" className="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || reason.trim().length<5}><UserCheck size={17}/> Save officer decision</button></div></form></Modal>;
}

export function DocumentViewer({document:doc,review,onClose}: {document:DocumentRecord;review:Review;onClose:()=>void}) {
  const [url,setUrl]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState('');
  useEffect(()=>{let objectUrl='';let active=true;fileBlob(`/documents/${doc.id}/file`).then(b=>{objectUrl=URL.createObjectURL(b);if(active)setUrl(objectUrl);}).catch(e=>setError(e.message));return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[doc.id]);
  const entities=review.entities.filter(e=>e.document_id===doc.id), entity=entities.find(e=>e.id===selected)||entities[0];
  const checks=review.verifications.filter(v=>v.evidence.document_id===doc.id);
  return <Modal title={doc.filename} onClose={onClose} wide><div className="viewer-toolbar"><Badge value={doc.classification}/><span>{percent(doc.extraction.ocr_confidence || 0)} extraction confidence</span><button className="text-button" onClick={()=>void download(`/documents/${doc.id}/file`,doc.filename).catch(e=>setError(e.message))}><Download size={15}/> Download original</button></div><ErrorBox message={error}/><div className="document-viewer"><section className="document-preview"><h3>01 / ORIGINAL DOCUMENT</h3>{url?(doc.mime_type==='application/pdf'?<iframe src={`${url}#page=${entity?.source_page || 1}`} title={`Original ${doc.filename}`}/>:<img src={url} alt={`Original ${doc.filename}`}/>):<p>Loading original document…</p>}</section><section className="extracted-pane"><h3>02 / EXTRACTED FIELDS</h3>{entities.length?entities.map(e=><button key={e.id} className={`extracted-field ${entity?.id===e.id?'selected':''} ${checks.some(v=>v.entity_id===e.id&&v.status==='MISMATCH')?'suspicious':''}`} onClick={()=>setSelected(e.id)}><span>{pretty(e.type)}<small>{percent(e.confidence)}</small></span><strong>{e.value}</strong><small>Page {e.source_page}{e.bounding_box.length?' · Bounding box available':''}</small></button>):<p className="subtle">No extracted fields. Run verification or upload a readable document.</p>}</section><section className="verification-pane"><h3>03 / FIELD EVIDENCE</h3><MockLabel/>{entity && <div className="selected-evidence"><small>SOURCE TEXT · PAGE {entity.source_page}</small><blockquote>{entity.source_text}</blockquote>{entity.bounding_box.length>0 && <p className="subtle">Bounding box: {entity.bounding_box.map(n=>n.toFixed(0)).join(', ')}</p>}</div>}{checks.map(v=><div className="field-check" key={v.id}><strong>{v.source}</strong><Badge value={v.status}/><dl><dt>Extracted</dt><dd className={v.status==='MISMATCH'?'field-mismatch':''}>{v.identifier || 'Unavailable'}</dd><dt>Source record</dt><dd>{v.evidence.source_value || 'Unavailable'}</dd></dl><p>{v.evidence.reason}</p></div>)}{!checks.length && <p className="subtle section-gap">This document supports tender rules or identity evidence; it has no direct source verification.</p>}</section></div><details className="raw-text"><summary>Raw extracted text & processing notes</summary>{doc.extraction.warnings?.map(w=><ErrorBox message={w} key={w}/>)}<pre>{doc.raw_text || 'No readable text extracted.'}</pre><small>Providers: {doc.extraction.providers?.join(', ')}<br/>SHA256: {doc.sha256}</small></details></Modal>;
}

export function EvidenceIntelligence({review,onDocument,onDecide,canDecide}: {review:Review;onDocument:(d:DocumentRecord)=>void;onDecide:()=>void;canDecide:boolean}) {
  const [selected,setSelected]=useState(''),[node,setNode]=useState(0);
  const signals=review.risk?.contributing_factors || [];
  const signal=signals.find(s=>s.id===selected)||signals[0];
  const rule=review.compliance.find(r=>signal?.rule_result_ids.includes(r.result_id));
  const ev=signal?.evidence[0]||rule?.evidence[0];
  const verification=review.verifications.find(v=>v.id===ev?.verification_id);
  const entity=review.entities.find(e=>e.id===(ev?.entity_id || verification?.entity_id));
  const doc=review.documents.find(d=>d.id===(ev?.document_id || entity?.document_id || verification?.evidence.document_id));
  const decision=review.decisions.find(d=>d.run_id===review.current_run_id);
  const lineage=[{title:'Document',value:doc?.filename || (signal?.type==='missing_mandatory_document'?'Missing document':'Document set'),id:doc?.id,icon:FileText},
    {title:'Extracted entity',value:entity?.value || 'Document presence / validity',id:entity?.id,icon:Fingerprint},
    {title:'Source check',value:verification?`${verification.source} · ${pretty(verification.status)}`:'Documentary rule check',id:verification?.id,icon:ShieldCheck},
    {title:'Tender rule',value:rule?`${rule.rule_code} · ${pretty(rule.status)}`:'Cross-document anomaly',id:rule?.result_id,icon:CheckCircle2},
    {title:'Risk signal',value:signal?`+${signal.points} risk points`:'No rule-based risk',id:signal?.id,icon:AlertTriangle},
    {title:'AI explanation',value:review.ai?.recommended_action || 'Pending',id:review.ai?.id,icon:Sparkles},
    {title:'Officer decision',value:decision?.decision || 'Awaiting officer',id:decision?.id,icon:UserCheck}];
  return <div className="stack"><Panel title="Evidence intelligence" subtitle="Select a finding, then follow its evidence from document to officer decision" action={<span className="advisory-chip">FULL TRACEABILITY</span>}><div className="finding-selector">{signals.map(s=><button className={`finding-pill ${signal?.id===s.id?'selected':''}`} key={s.id} onClick={()=>{setSelected(s.id);setNode(0);}}><AlertTriangle size={15}/>{pretty(s.type)}<span>+{s.points}</span></button>)}{!signals.length && <div className="inline-notice">{review.risk?'No risk findings in this run. Explore individual checks in Government Verification.':'Run verification to build the evidence chain.'}</div>}</div><div className="lineage-graph">{lineage.map((n,i)=><div className="lineage-step" key={n.title}><button onClick={()=>setNode(i)} className={`lineage-node ${node===i?'selected':''}`}><span className="node-icon"><n.icon size={19}/></span><small>{String(i+1).padStart(2,'0')} / {n.title}</small><strong>{n.value}</strong><span className="node-status">{n.id?'Evidence linked':'Context / pending'}</span></button>{i<6 && <ArrowRight className="lineage-arrow" size={17}/>}</div>)}</div><div className="lineage-inspector"><div><div className="eyebrow">INSPECTING {lineage[node].title.toUpperCase()}</div><h3>{lineage[node].value}</h3><p>{node===0?(doc?'Open the submitted original and inspect the extracted fields.':'The required document is absent. This is an absence finding; no document or identifier was invented.'):node===1?(entity?.source_text || 'This finding is based on the submitted document set.'):node===2?(verification?.evidence.reason || 'Evaluated directly against documentary tender requirements.'):node===3?(rule?.explanation || 'Cross-document consistency check.'):node===4?(signal?.description || 'No signal selected.'):node===5?(review.ai?.summary || 'Explanation pending.'):decision?decision.reason:'The procurement officer must review this evidence and record a separate decision.'}</p>{lineage[node].id && <code>{lineage[node].id}</code>}</div>{node===0&&doc&&<button className="button" onClick={()=>onDocument(doc)}><FileText size={16}/> Open original</button>}{node===6&&canDecide&&<button className="button primary" onClick={onDecide}>Record decision <ArrowRight size={16}/></button>}</div></Panel>{review.ai && <RecommendationPanel review={review} onDecide={onDecide} canDecide={canDecide}/>}</div>;
}
