"""Readable fictional PDF fixtures; no real personal or government records."""
from io import BytesIO
from xml.sax.saxutils import escape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

TITLES = {'pan': 'PAN Card - Permanent Account Number', 'gst_certificate': 'GST Registration Certificate',
          'udyam': 'Udyam Registration', 'oem_authorization': 'OEM Authorization',
          'experience_certificate': 'Experience Certificate', 'tax_compliance': 'Tax Compliance Statement',
          'incorporation': 'Certificate of Incorporation', 'bank_certificate': 'Bank Certificate'}


def make_sample(name: str, kind: str, fields: dict[str, str]) -> bytes:
    stream = BytesIO()
    pdf = SimpleDocTemplate(stream, pagesize=(210*mm, 297*mm), rightMargin=22*mm, leftMargin=22*mm,
                            topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Brand', fontSize=11, textColor=colors.HexColor('#167d80'), spaceAfter=18))
    styles.add(ParagraphStyle(name='DocTitle', fontSize=24, leading=29, textColor=colors.HexColor('#12243c'), spaceAfter=20))
    styles.add(ParagraphStyle(name='Field', fontSize=11, leading=18, spaceAfter=9))
    story = [Paragraph('BYTECODE VERIFY / FICTIONAL SAMPLE', styles['Brand']),
             Paragraph(TITLES[kind], styles['DocTitle']),
             Paragraph('MOCK AUTHORISED SOURCE - DEMO', styles['Heading3']),
             Paragraph('For prototype demonstration only. This is not an official certificate.', styles['BodyText']),
             Spacer(1, 16*mm), Paragraph('Company Name: '+escape(name), styles['Field'])]
    for label, value in fields.items():
        story.append(Paragraph(escape(f'{label}: {value}'), styles['Field']))
    story.extend([Spacer(1, 20*mm), Paragraph('Fictional document generated by Team ByteCode. All entities and identifiers are synthetic.', styles['BodyText'])])
    def footer(canvas, doc):
        canvas.setStrokeColor(colors.HexColor('#d9e1e8'))
        canvas.line(22*mm, 18*mm, 188*mm, 18*mm)
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(colors.HexColor('#617185'))
        canvas.drawString(22*mm, 12*mm, 'SIH 2026 | Problem Statement 26100 | Decision support only')
        canvas.drawRightString(188*mm, 12*mm, str(doc.page))
    pdf.build(story, onFirstPage=footer, onLaterPages=footer)
    return stream.getvalue()
