export interface User { id: string; name: string; email: string; role: 'BIDDER' | 'PROCUREMENT_OFFICER' | 'AUDITOR' | 'ADMIN' }
export interface Stage { name: string; status: string; detail?: string; started_at?: string; completed_at?: string }
export interface Run { id: string; bid_id: string; status: string; stages: Stage[]; error?: string; created_at: string; completed_at?: string }
export interface TenderRequirement { id: string; requirement_code: string; type: string; label: string; mandatory: boolean; accepted_evidence: string[]; exemptions: string[]; source_page?: number; source_text: string; confidence: number; status: string }
export interface TenderDocument { id: string; url: string; document_type: string; sha256: string; fetch_status: string }
export interface Tender { id: string; reference: string; title: string; department: string; deadline: string; description: string; required_documents: string[]; scoring_weights: Record<string, number>; local_content_threshold: number; source?: string; external_bid_id?: string; source_url?: string; organisation?: string; ministry?: string; category?: string; status?: string; requirement_count?: number; bidder_count?: number; pending?: number; average_compliance?: number; highest_risk?: string; review_status?: string; bids?: Bid[]; rules?: Rule[]; requirements?: TenderRequirement[]; tender_documents?: TenderDocument[] }
export interface Bidder { id: string; name: string; pan: string; gstin: string; udyam: string; address: string; profile: Record<string, unknown> }
export interface Bid { id: string; scenario: string; status: string; final_decision: string | null; current_run_id: string | null; submitted_by_user_id?: string | null; bidder: Bidder; tender: Tender; compliance_score: number | null; risk_score: number | null; risk_level: string; issues: number }
export interface DocumentRecord { id: string; filename: string; mime_type: string; classification: string; raw_text: string; normalized_text: string; sha256: string; pages: {page_number: number; text: string; provider: string; confidence: number}[]; extraction: { warnings?: string[]; ocr_confidence?: number; providers?: string[] }; is_seed: boolean }
export interface Entity { id: string; document_id: string; type: string; value: string; normalized_value: string; confidence: number; source_page: number; source_text: string; bounding_box: number[] }
export interface Evidence { document_id?: string; entity_id?: string; verification_id?: string; source?: string; extracted?: string; source_value?: string; status?: string; filename?: string; source_page?: number }
export interface Verification { id: string; source: string; status: string; entity_id?: string; identifier: string; record: Record<string, unknown>; confidence: number; checked_at: string; is_mock: boolean; evidence: {extracted_value?: string; source_value?: string; reason: string; document_id?: string; source_page?: number; conflicting_values?: string[]} }
export interface Rule { id: string; rule_id: string; name: string; category: string; expression: Record<string, any>; severity: string; required: boolean; enabled: boolean }
export interface RuleResult { result_id: string; rule_id: string; rule_code: string; name: string; status: string; severity: string; category: string; required: boolean; explanation: string; expression: Record<string, any>; evidence: Evidence[] }
export interface Signal { id: string; type: string; description: string; points: number; evidence: Evidence[]; rule_result_ids: string[] }
export interface ScorePart { component: string; weight: number; earned: number; lost: number; passed: number; total: number; evidence: string[] }
export interface Risk { risk_score: number; risk_level: string; method: string; contributing_factors: Signal[]; compliance: {score: number; maximum: number; breakdown: ScorePart[]; method: string}; identity_checks: {label: string; status: string; similarity?: number; left?: string; right?: string; provider?: string}[]; anomaly: {anomaly_score: number | null; detector: string; explanation: string; features: Record<string, number>; anomalies: string[]} }
export interface Recommendation { id: string; provider: string; summary: string; recommended_action: string; confidence: number; confidence_explanation: string; why: string[]; officer_action: string; evidence: {rule_result_id: string; rule_code: string; rule: string; status: string; details: Evidence[]}[]; reasoning_sources: {sources: {id: string; title: string; text: string; kind: string; relevance: number}[]; vector_provider: string; embedding_provider: string; scope: string} }
export interface Decision { id: string; run_id: string; reviewer: string; decision: string; reason: string; comments: string; ai_recommendation: string; is_override: boolean; created_at: string }
export interface Review extends Bid { documents: DocumentRecord[]; run: Run | null; entities: Entity[]; verifications: Verification[]; compliance: RuleResult[]; risk: Risk | null; ai: Recommendation | null; decisions: Decision[] }
export interface AuditEvent { id: string; sequence: number; bid_id: string; actor: string; action: string; object_id: string; object_type: string; role: string; created_at: string; current_hash: string; previous_hash: string; evidence_hash: string; details: Record<string, any> }
export interface Integrity { status: string; checked_events: number; head_hash: string; limitation?: string }
export interface AuditData { integrity: Integrity; events: AuditEvent[] }
export interface ChartDatum { name: string; value: number }
export interface DashboardData { total_tenders: number; total_bids: number; total_documents: number; active_reviews: number; high_risk_bids: number; pending_decisions: number; average_compliance: number | null; issues_detected: number; assessed_bids: number; compliance_distribution: ChartDatum[]; risk_distribution: ChartDatum[]; verification_status: ChartDatum[]; review_throughput: ChartDatum[]; recent_events: AuditEvent[]; priority_bids: Bid[]; integrity: Integrity }
