import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Code2, Save, ShieldCheck } from 'lucide-react';
import { request, useApi } from '../services/api';
import type { Tender, User } from '../types';
import { ErrorBox, Loading, PageHeading, Panel } from '../components/ui';
export default function AdminRules({user}:{user:User}){
  const {data:tenders,error}=useApi<Tender[]>('/tenders');const [params,setParams]=useSearchParams();
  const [selected,setSelected]=useState(params.get('tender')||''),[code,setCode]=useState(''),[message,setMessage]=useState(''),[editError,setEditError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{if(tenders?.length&&!selected)setSelected(tenders[0].id);},[tenders,selected]);
  useEffect(()=>{if(selected){setMessage('');request<Tender>(`/tenders/${selected}`).then(t=>{setCode(JSON.stringify({rules:t.rules?.map(({created_at,...r}:any)=>r),scoring_weights:t.scoring_weights},null,2));setEditError('');}).catch(e=>setEditError(e.message));}},[selected]);
  async function save(){setBusy(true);setEditError('');try{const body=JSON.parse(code);const r=await request<{message:string}>(`/tenders/${selected}/rules`,{method:'PUT',body:JSON.stringify(body)});setMessage(r.message);}catch(e){setEditError((e as Error).message);}finally{setBusy(false);}}
  if(!tenders)return error?<ErrorBox message={error}/>:<Loading/>;
  return <><PageHeading eyebrow="TENDER CONFIGURATION" title="Compliance rules" description="Configure requirements and score weights. Every change is audited." actions={user.role==='ADMIN'?<button className="button primary" disabled={busy||!code} onClick={()=>void save()}><Save size={16}/> Save rule configuration</button>:undefined}/><ErrorBox message={error||editError}/>{message&&<div role="status" className="success-box"><ShieldCheck size={18}/>{message}</div>}<div className="rules-layout"><Panel title="Tender rule configuration" action={<Code2 size={20}/>}><div className="toolbar"><select aria-label="Select tender for rule editor" value={selected} onChange={e=>{setSelected(e.target.value);setParams({tender:e.target.value});}}>{tenders.map(t=><option key={t.id} value={t.id}>{t.reference}</option>)}</select><span className="toolbar-count">{user.role==='ADMIN'?'JSON editor':'Read-only'}</span></div><textarea className="json-editor" aria-label="Tender rules JSON" spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} readOnly={user.role!=='ADMIN'}/></Panel><div className="stack"><Panel title="Supported rule operators"><div className="content-pad operator-guide">{[['source_status','A named source must return VERIFIED.'],['document_present','A readable document with this classification is required.'],['valid_documents','Certificate validity is compared with the tender deadline.'],['minimum_field','A declared numerical value must meet the threshold.']].map(([op,description])=><div key={op}><code>{op}</code><p>{description}</p></div>)}</div></Panel><Panel title="Configuration safeguards"><div className="content-pad"><p className="subtle">The six component weights must total 100. Rules use a restricted expression schema; executable code is never evaluated.</p><p className="inline-notice section-gap">Saved changes apply to future runs. Existing findings retain their original rule expression and score breakdown.</p>{user.role!=='ADMIN'&&<p className="subtle section-gap">Sign in with the demo administrator account to edit rules.</p>}</div></Panel></div></div></>;
}
