import { useState } from 'react';
import { Download, Fingerprint, Search, ShieldCheck } from 'lucide-react';
import { download, useApi } from '../services/api';
import type { AuditData } from '../types';
import { Badge, Empty, ErrorBox, Loading, PageHeading, Panel, dateTime, pretty } from '../components/ui';
export default function AuditTrail({bidId,embedded=false}:{bidId?:string;embedded?:boolean}){
  const {data,error}=useApi<AuditData>(`/audit${bidId?`?bid_id=${bidId}`:''}`,5000),[filter,setFilter]=useState(''),[exportError,setExportError]=useState(''),[busy,setBusy]=useState(false);
  async function exportReport(){setBusy(true);try{await download(`/audit/export${bidId?`?bid_id=${bidId}`:''}`,'bytecode-audit-report.pdf');}catch(e){setExportError((e as Error).message);}finally{setBusy(false);}}
  if(!data)return error?<ErrorBox message={error}/>:<Loading/>;
  const events=data.events.filter(e=>`${e.action} ${e.actor} ${e.object_id}`.toLowerCase().includes(filter.toLowerCase()));
  return <>{!embedded&&<PageHeading eyebrow="GOVERNANCE & ACCOUNTABILITY" title="Audit trail" description="A tamper-evident record of the evidence, recommendations, and officer decisions." actions={<button className="button" disabled={busy} onClick={()=>void exportReport()}><Download size={17}/> Export audit report</button>}/>}<ErrorBox message={error||exportError}/><div className="audit-integrity"><span className="integrity-icon"><ShieldCheck size={27}/></span><div><h3>Audit integrity: {data.integrity.status}</h3><p>{data.integrity.checked_events} events checked across the entire application chain</p></div><Badge value={data.integrity.status}/><details><summary>Inspect chain head</summary><code>{data.integrity.head_hash}</code><p>Application-layer append-only records. Database administrators can still modify underlying storage.</p></details></div><Panel title={embedded?'Bid review audit history':'Event timeline'} subtitle={`${events.length} events in this view`} action={embedded?<button className="text-button" onClick={()=>void exportReport()} disabled={busy}><Download size={15}/> Export PDF</button>:undefined}><div className="toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search audit events" placeholder="Filter action, reviewer, or object ID…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><span className="toolbar-count">Most recent first</span></div><div className="audit-events">{events.slice(0,150).map(e=><details className="audit-event" key={e.id}><summary><span className={`audit-event-icon ${e.action.includes('OFFICER')||e.action.includes('DECISION')?'officer':''}`}><Fingerprint size={18}/></span><div><strong>{pretty(e.action)}</strong><p>{e.actor} <span>· {pretty(e.role)}</span></p></div><div className="audit-event-time"><strong>{dateTime(e.created_at)}</strong><small>Event #{e.sequence}</small></div></summary><div className="audit-event-detail"><div className="label-value"><span>Object</span><code>{e.object_type}: {e.object_id}</code></div>{e.details.reason&&<div className="decision-reason"><strong>Officer reason</strong><p>{e.details.reason}</p></div>}<pre>{JSON.stringify(e.details,null,2)}</pre><div className="hash-row"><span>Previous hash</span><code>{e.previous_hash}</code></div><div className="hash-row"><span>Current hash</span><code>{e.current_hash}</code></div><div className="hash-row"><span>Evidence hash</span><code>{e.evidence_hash}</code></div></div></details>)}{!events.length&&<Empty title="No matching events">Try a different filter.</Empty>}{events.length>150&&<p className="subtle content-pad">Showing the latest 150 matches. Export PDF for the full record.</p>}</div></Panel></>;
}
