import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Search } from 'lucide-react';
import { useApi } from '../services/api';
import type { Bid } from '../types';
import { BidTable, ErrorBox, Loading, SourceStatus, PageHeading, Panel } from '../components/ui';
export default function BidList({mode='bids'}:{mode?:'bids'|'verification'|'risk'}){
  const {data,error}=useApi<Bid[]>('/bids',4000),[search,setSearch]=useState(''),[risk,setRisk]=useState('ALL');
  if(!data)return error?<ErrorBox message={error}/>:<Loading/>;
  const title=mode==='verification'?'Verification workspace':mode==='risk'?'Risk intelligence':'Bid review queue';
  const bids=data.filter(b=>b.bidder.name.toLowerCase().includes(search.toLowerCase())&&(risk==='ALL'||b.risk_level===risk)).sort((a,b)=>mode==='risk'?(b.risk_score||0)-(a.risk_score||0):0);
  return <><PageHeading eyebrow={mode==='risk'?'EVIDENCE-BASED RISK ANALYSIS':'BID COMPLIANCE OPERATIONS'} title={title} description={mode==='verification'?'Inspect extracted identifiers and the results of 11 mock source checks.':mode==='risk'?'Trace every risk point to a source mismatch, document, or tender rule.':'Open a bid to verify documents and record an officer decision.'} actions={<Link className="button" to="/tenders">Browse tenders <ArrowRight size={16}/></Link>}/><ErrorBox message={error}/>{mode==='verification'&&<div className="demo-banner"><span>11 source adapters · Document-level evidence · Field confidence</span><SourceStatus/></div>}{mode==='risk'&&<div className="metrics-grid">{['LOW','MEDIUM','HIGH','CRITICAL'].map(level=><div className="metric-card" key={level}><div className="metric-top">{level} RISK</div><strong className="metric-value">{data.filter(b=>b.risk_level===level).length}</strong><p>{level==='LOW'?'0–19':level==='MEDIUM'?'20–44':level==='HIGH'?'45–79':'80–100'} risk points</p></div>)}</div>}<Panel title={mode==='verification'?'Bidder verification records':mode==='risk'?'Bids ranked by risk':'All submitted bids'} subtitle="Live assessment and officer review status"><div className="toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search bidders" placeholder="Search bidder name…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter risk level" value={risk} onChange={e=>setRisk(e.target.value)}><option value="ALL">All risk levels</option>{['LOW','MEDIUM','HIGH','CRITICAL','UNASSESSED'].map(r=><option key={r}>{r}</option>)}</select><span className="toolbar-count">{bids.length} bids</span></div><BidTable bids={bids}/></Panel>{mode==='verification'&&<Panel className="section-gap" title="Open source evidence directly"><div className="source-links">{bids.map(b=><Link key={b.id} to={`/bids/${b.id}?tab=Government+Verification`}><span>{b.bidder.name}</span><ArrowRight size={16}/></Link>)}</div></Panel>}</>;
}
