import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, FileWarning, Fingerprint, Play, ShieldAlert, Sparkles, Timer, UserCheck } from 'lucide-react';
import type { Review, Run, User } from '../types';
import { post, useApi } from '../services/api';
import { Badge, ErrorBox, Loading, MockLabel, PageHeading, Panel, ProcessingTimeline } from '../components/ui';
import { OfficerDecisionModal, ScoreCards } from '../components/ReviewPanels';
interface Scenario{id:string;name:string;description:string;bid_id:string}
const icons=[CheckCircle2,Fingerprint,FileWarning,FileWarning,ShieldAlert,ShieldAlert,UserCheck];
export default function Demo({user}:{user:User}){
  const {data:scenarios,error}=useApi<Scenario[]>('/demo/scenarios');const [selected,setSelected]=useState('MULTI_RISK'),[bidId,setBidId]=useState(''),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false);
  async function start(){setBusy(true);setActionError('');try{const run=await post<Run>(`/demo/run/${selected}`);setBidId(run.bid_id);}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
  if(!scenarios)return error?<ErrorBox message={error}/>:<Loading/>;
  return <><PageHeading eyebrow="SIH 2026 · TEAM BYTECODE" title="Executive verification demo" description="From submitted documents to an evidence-backed officer decision." actions={<MockLabel/>}/><ErrorBox message={error||actionError}/><div className="demo-intro"><span className="demo-intro-icon"><Sparkles size={27}/></span><div><h2>One bid. A complete evidence trail.</h2><p>Choose a fictional scenario and watch the actual verification pipeline run.</p></div><span className="demo-time"><Timer size={16}/> Designed for a live walkthrough</span></div><div className="scenario-grid">{scenarios.map((s,i)=>{const Icon=icons[i];return <button className={`scenario-card ${selected===s.id?'selected':''}`} onClick={()=>setSelected(s.id)} key={s.id}><div><Icon size={21}/><span className="scenario-radio"/></div><h3>{s.name}</h3><p>{s.description}</p>{s.id==='MULTI_RISK'&&<span className="flagship-chip">FLAGSHIP DEMO</span>}</button>;})}</div><div className="demo-run-bar"><div><strong>{scenarios.find(s=>s.id===selected)?.name}</strong><span>All findings come from the selected bid's current documents.</span></div><button className="button primary" disabled={busy||user.role==='AUDITOR'} onClick={()=>void start()}><Play size={17}/> {busy?'Starting…':'Run verification'}</button></div>{user.role==='AUDITOR'&&<p className="inline-notice">Auditors have read-only access. Sign in as a procurement officer to start a demo run.</p>}{bidId?<DemoRun key={bidId} bidId={bidId} user={user}/>:<Panel className="section-gap" title="The live review journey"><div className="demo-journey">{['Upload & extract','Verify sources','Evaluate rules','Explain risk','Officer decides'].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong>{i<4&&<ArrowRight size={20}/>}</div>)}</div><div className="inline-notice">Demo verified means a match against a fictional source record. No government connectivity or independent eligibility certification is implied.</div></Panel>}</>;
}
function DemoRun({bidId,user}:{bidId:string;user:User}){
  const {data:review,error,reload}=useApi<Review>(`/bids/${bidId}`,1000),{data:status}=useApi<{run:Run|null}>(`/bids/${bidId}/status`,700),[decide,setDecide]=useState(false);
  if(!review)return error?<ErrorBox message={error}/>:<Loading/>;
  const run=status?.run||review.run,complete=run?.status==='COMPLETED';
  const decision=review.decisions.find(d=>d.run_id===review.current_run_id);
  return <div className="demo-results section-gap"><Panel title="Live processing timeline" subtitle={review.bidder.name} action={<Badge value={run?.status}/>}><ProcessingTimeline run={run}/></Panel><div className="stack"><ScoreCards review={review}/><Panel title="Verification outcome" subtitle="Advisory findings from the current processing run"><div className="content-pad">{complete&&review.ai?<><span className="demo-chip">{review.ai.recommended_action}</span><p className="demo-summary">{review.ai.summary}</p><div className="demo-findings">{review.compliance.filter(r=>r.status==='FAIL').map(r=><div key={r.result_id}><Badge value="FAIL"/><span>{r.rule_code} · {r.explanation}</span></div>)}</div>{decision?<div className="officer-decision-banner"><UserCheck size={23}/><div><h3>{decision.decision}</h3><p>{decision.reason}</p></div></div>:user.role!=='AUDITOR'&&<button className="button primary" onClick={()=>setDecide(true)}><UserCheck size={17}/> Record officer decision</button>}<Link className="button section-gap" to={`/bids/${bidId}`}>Open full evidence review <ArrowRight size={16}/></Link></>:<p className="subtle">{run?.error||'Results appear here as the actual pipeline saves its findings. The officer decision remains separate.'}</p>}</div></Panel></div>{decide&&<OfficerDecisionModal review={review} onClose={()=>setDecide(false)} onSaved={()=>void reload()}/>}</div>;
}
