import { useState } from 'react';
import { ArrowRight, FileCheck2, Fingerprint, ShieldCheck, UserCheck, Workflow } from 'lucide-react';
import { post } from '../services/api';
import type { User } from '../types';
import { ErrorBox } from '../components/ui';
export default function Login({ onLogin }: {onLogin: (user: User, token: string) => void}) {
  const [email, setEmail] = useState('officer@bytecode.demo'), [password, setPassword] = useState('officer123');
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function signIn(role?: string) {
    setBusy(true); setError('');
    try { const result = await post<{user: User; access_token: string}>(role ? '/auth/demo-login' : '/auth/login', role ? {role} : {email, password}); onLogin(result.user, result.access_token); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <div className="login-page"><aside className="login-story"><div className="brand"><div className="brand-mark"><ShieldCheck/></div><span>ByteCode <b>Verify</b></span></div><div className="login-story-main"><div className="eyebrow">PROCUREMENT, WITH CONFIDENCE</div><h1>Every bid.<br/>Every check.<br/><em>Evidence first.</em></h1><p>AI-Powered Bid Compliance Verification Platform</p><div className="login-flow">{[[FileCheck2, 'Extract the facts'], [Fingerprint, 'Trace the evidence'], [UserCheck, 'Make the decision']].map(([Icon, label]) => { const I = Icon as typeof FileCheck2; return <div key={String(label)}><I size={23}/><span>{String(label)}</span><ArrowRight size={16}/></div>; })}</div></div><div className="login-footer">TEAM BYTECODE <span>SIH 2026 · PS 26100</span></div></aside><main className="login-form-side"><div className="login-form"><span className="demo-chip">LOCAL DEMONSTRATION</span><h2>Welcome to your<br/>verification workspace.</h2><p>Review evidence. Apply tender rules. Keep the final decision in your hands.</p><ErrorBox message={error}/><form onSubmit={e=>{e.preventDefault(); void signIn();}}><label>Demo email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Demo password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button className="button primary full" disabled={busy}>Sign in to workspace <ArrowRight size={17}/></button></form><div className="divider-label">OR USE A DEMO ACCOUNT</div><button disabled={busy} className="button full" onClick={()=>void signIn('PROCUREMENT_OFFICER')}><UserCheck size={18}/> Login as Procurement Officer</button><button disabled={busy} className="button full" onClick={()=>void signIn('AUDITOR')}><ShieldCheck size={18}/> Login as Auditor</button><button disabled={busy} className="text-button admin-login" onClick={()=>void signIn('ADMIN')}>Demo administrator · Rule configuration <ArrowRight size={13}/></button><div className="login-note"><Workflow size={21}/><p>All source checks use clearly labeled fictional records. This prototype does not connect to government portals.</p></div><small>Demo credentials: officer@bytecode.demo / officer123<br/>auditor@bytecode.demo / auditor123</small></div></main></div>;
}
