import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, CalendarDays, FileStack, Plus, Search, Sparkles } from 'lucide-react';
import type { Bid, Tender, User } from '../types';
import { post, useApi } from '../services/api';
import { Badge, BidTable, ErrorBox, Loading, Modal, PageHeading, Panel, dateTime, pretty } from '../components/ui';
export function TenderList({user}:{user:User}){
  const {data,error,reload}=useApi<Tender[]>('/tenders',5000),[search,setSearch]=useState(''),[create,setCreate]=useState(false);
  if(!data)return error?<ErrorBox message={error}/>:<Loading/>;
  return <><PageHeading eyebrow="PROCUREMENT PORTFOLIO" title="Tenders" description="Manage requirements and review bidder compliance across your tenders." actions={user.role!=='AUDITOR'?<button className="button primary" onClick={()=>setCreate(true)}><Plus size={17}/> Create tender</button>:undefined}/><ErrorBox message={error}/><div className="tender-summary"><FileStack size={22}/><strong>{data.length} tenders</strong><span>{data.reduce((n,t)=>n+(t.bidder_count||0),0)} participating bids</span><span>{data.reduce((n,t)=>n+(t.pending||0),0)} decisions pending</span></div><Panel><div className="toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search tenders" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tender title or reference…"/></div></div><div className="table-scroll"><table className="tender-table"><thead><tr><th>Tender / department</th><th>Deadline</th><th>Bids</th><th>Review status</th><th>Highest risk</th><th>Avg. compliance</th><th>Action</th></tr></thead><tbody>{data.filter(t=>`${t.title} ${t.reference}`.toLowerCase().includes(search.toLowerCase())).map(t=><tr key={t.id}><td><Link to={`/tenders/${t.id}`}><small className="tender-reference">{t.reference}</small><strong className="tender-title">{t.title}</strong><small className="block-small">{t.department}</small></Link></td><td>{dateTime(t.deadline)}</td><td>{t.bidder_count}</td><td><Badge value={t.review_status}/></td><td><Badge value={t.highest_risk}/></td><td><strong>{t.average_compliance ?? '—'}</strong><small> /100</small></td><td><Link className="text-button" to={`/tenders/${t.id}`}>Open <ArrowRight size={14}/></Link></td></tr>)}</tbody></table></div></Panel>{create&&<CreateTender onClose={()=>setCreate(false)} onSaved={()=>void reload()}/>}</>;
}
function CreateTender({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);const navigate=useNavigate();
  return <Modal title="Create procurement tender" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const tender=await post<Tender>('/tenders',{reference:f.get('reference'),title:f.get('title'),deadline:f.get('deadline'),description:f.get('description')});onSaved();onClose();navigate(`/tenders/${tender.id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div className="modal-body"><ErrorBox message={error}/><label>Tender reference<input name="reference" required minLength={3} placeholder="CPCL/2026/PROC/006"/></label><label>Title<input name="title" required minLength={5} placeholder="Supply of industrial equipment"/></label><label>Submission deadline<input type="datetime-local" name="deadline" required/></label><label>Description<textarea name="description"/></label><div className="inline-notice section-gap">The standard eight-rule compliance template is applied. An administrator can adjust its JSON configuration.</div></div><div className="modal-actions"><button type="button" className="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>Create tender</button></div></form></Modal>;
}
export function TenderDetail({user}:{user:User}){
  const {tenderId}=useParams();const {data,error,reload}=useApi<Tender>(`/tenders/${tenderId}`,4000),[create,setCreate]=useState(false),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false);
  if(!data)return error?<ErrorBox message={error}/>:<Loading/>;
  async function startAll(){setBusy(true);setActionError('');try{for(const b of data?.bids || []){if(b.status!=='PROCESSING')await post(`/bids/${b.id}/process`);}await reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
  return <><Link to="/tenders" className="back-link"><ArrowLeft size={14}/> All tenders</Link><PageHeading eyebrow={data.reference} title={data.title} description={data.department} actions={user.role!=='AUDITOR'?<button className="button primary" disabled={busy||!data.bids?.length} onClick={()=>void startAll()}><Sparkles size={17}/> Start AI Compliance Review</button>:undefined}/><ErrorBox message={error||actionError}/><div className="tender-detail-meta"><span><CalendarDays size={17}/> Submission: {dateTime(data.deadline)}</span><span>{data.bids?.length} bids</span><span>{data.rules?.filter(r=>r.enabled).length} active tender rules</span><Badge value={data.bids?.every(b=>b.final_decision)&&data.bids.length?'COMPLETED':'IN REVIEW'}/></div><div className="stack"><div className="two-col"><Panel title="Tender requirements"><div className="content-pad"><p className="tender-description">{data.description}</p><div className="label-value"><span>Minimum local content</span><strong>{data.local_content_threshold}% declared</strong></div><div className="required-docs">{data.required_documents.map(d=><span key={d}><FileStack size={14}/>{pretty(d)}</span>)}</div></div></Panel><Panel title="Compliance template" subtitle="JSON-configurable tender requirements" action={<Link className="text-button" to={`/rules?tender=${data.id}`}>View rules <ArrowRight size={14}/></Link>}><div className="template-rules">{data.rules?.map(r=><div key={r.id}><code>{r.rule_id}</code><span>{r.name}</span><Badge value={r.enabled?'ACTIVE':'DISABLED'}/></div>)}</div></Panel></div><Panel title="Participating bidders" subtitle="Review documents, findings, and officer decisions" action={user.role!=='AUDITOR'?<button className="text-button" onClick={()=>setCreate(true)}><Plus size={15}/> Add bidder</button>:undefined}><BidTable bids={data.bids||[]}/></Panel><Panel title="Tender review timeline" subtitle="Latest processing and decision state for each participating bid"><div className="content-pad">{data.bids?.map(b=><div className="label-value" key={b.id}><Link to={`/bids/${b.id}?tab=Audit+Trail`}>{b.bidder.name}</Link><Badge value={b.final_decision||b.status}/></div>)}</div></Panel></div>{create&&<CreateBid tender={data} onClose={()=>setCreate(false)} onSaved={()=>void reload()}/>}</>;
}
export function CreateBid({tender,onClose,onSaved}:{tender:Tender;onClose:()=>void;onSaved:()=>void}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);const navigate=useNavigate();
  return <Modal title="Add bidder to tender" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const bid=await post<Bid>('/bids',{tender_id:tender.id,...Object.fromEntries(f)});onSaved();onClose();navigate(`/bids/${bid.id}?tab=Documents`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div className="modal-body"><ErrorBox message={error}/><p className="subtle">{tender.reference}</p><label className="section-gap">Company name<input name="name" minLength={3} required/></label><label>PAN<input name="pan" required pattern="[A-Z]{5}[0-9]{4}[A-Z]" placeholder="ABCDE1234F"/></label><label>GSTIN<input name="gstin" required minLength={15} maxLength={15}/></label><label>Udyam number<input name="udyam"/></label><label>Address<textarea name="address"/></label><p className="inline-notice section-gap">New identities will not appear in the fictional source registry. Unmatched checks correctly return “not found” for officer review.</p></div><div className="modal-actions"><button className="button" type="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>Add bidder & upload</button></div></form></Modal>;
}
